"""Stage 1: Overview report generator (15 min reading)."""

from __future__ import annotations

import json
from datetime import date, datetime

from src.llm.client import LLMClient
from src.logging_config import get_logger
from src.models.analysis import AnalyzedItem
from src.models.report import DailyOverview, IndexEntry, ReportSection
from src.storage.local_store import LocalStore

logger = get_logger("reporters.overview")


class OverviewReporter:
    """Generates the Stage 1 daily overview report."""

    def __init__(self, llm: LLMClient, store: LocalStore):
        self.llm = llm
        self.store = store

    async def generate(self, target_date: date, items: list[AnalyzedItem]) -> tuple[DailyOverview, str]:
        """Generate the overview report.

        Returns:
            Tuple of (DailyOverview model, markdown string)
        """
        logger.info("Generating overview report for %s with %d items", target_date, len(items))

        # Build index
        index_entries = [
            IndexEntry(
                index=item.index,
                category=item.category,
                title=item.source_item.title,
                source=item.source_item.source_name,
                url=item.source_item.url,
            )
            for item in items
        ]

        # Generate report via LLM
        items_json = json.dumps(
            [item.model_dump(mode="json") for item in items],
            ensure_ascii=False,
            indent=2,
        )

        markdown = self.llm.generate_with_template(
            "overview_report",
            {
                "date": target_date.isoformat(),
                "total_items": len(items),
                "analyzed_items": items_json,
            },
            max_tokens=16384,
            temperature=0.3,
        )

        # Build sections from items (for the data model)
        sections = self._build_sections(items)

        overview = DailyOverview(
            date=target_date,
            summary=f"今日共收录 {len(items)} 条信息。",
            sections=sections,
            item_index=index_entries,
            total_items=len(items),
            generation_time=datetime.now(),
        )

        # Save both data model and markdown
        self.store.save_model(
            f"reports/{target_date.isoformat()}/overview_model.json", overview
        )
        self.store.save_report(target_date, "overview.md", markdown)
        output_path = self.store.save_output(target_date, "daily_report.md", markdown)

        logger.info("Overview report saved to %s", output_path)
        return overview, markdown

    def _build_sections(self, items: list[AnalyzedItem]) -> list[ReportSection]:
        """Group items by category into report sections."""
        categories: dict[str, list[AnalyzedItem]] = {}
        for item in items:
            categories.setdefault(item.category, []).append(item)

        sections = []
        for cat_name, cat_items in categories.items():
            sections.append(ReportSection(
                category=cat_name,
                items_markdown="",  # Markdown is generated by LLM as a whole
                item_count=len(cat_items),
            ))
        return sections
